[book]
authors = ["abhitopia"]
language = "en"
multilingual = false
src = "src"
title = "Abhitopia Blog Test 123. And yet again!"

[preprocessor]

[preprocessor.katex]
after = ["links"]

# [preprocessor.pagetoc]

[output]

[output.html]
additional-css = ["./theme/pagetoc.css"]
additional-js = ["./theme/pagetoc.js"]
